language: go

go:
  - 1.12

env:
  global:
    # coveralls repo token
    - secure: N9SmiHqmT62JBF4+ChXXrYKdIfTZ7nHkcQHnSRzyZ4ii00uY9g9w/8nWPGaGBJ4WGoaCUJx+VkVCS1UOf/UbZ8CqST89LE5EFc2N4AnqFSA3iRA3BlTb1OehppdYSA9GdrmX+NbaDJNdaqgOiz+JpBvbno2+hP0jXQPPqEhQKlRlP+I4QlwYtWiHm+iwoNP88kmunBj+G/qe79kq0qflQOFcZQIujORWjNLGNKepA06Bnb3Yi42EihXCQP7BbXWgKhp3SVTvIAL7wfEYjTOmPRXvU+bs8O7DI/C002CfnyiE00/KzKNaD+ICRiBh33ew3wD3FraLuXlWJ9BDNXKjfv04y0Mif/oERHc2Y08BNuQAFnlD2QCMrze6bRrJRf0Z5wD9tQn52BhP6w9qnxmMXitDu+j9uUj81wNz9uiEdFm+bZvn0HKHcgMzye9VCsPXRhmAABlr9XlGY+vjiiaguiWM/d6x87CtTBZva9FVZkfd3UY61X2L4vSIYuGOQe86GJFb4w8u71iD1Do4lnp/mKXRymeUgMTWIyF2meZK/7gF1TwLxskmvgeEBZ7uTSpsU+iNuIV4hzmPn5IAQgQQc4RqFPOHP7ZqvRvA++cImTHk5IW78KW0B2Ca2QPJHXNekHuAMJV65VSnhh4h4r3GpLh15rAMqx+Ud2BFsRzWxuY=

before_script:
  - make install

script:
  - make lint
  - make test && make coverage
  - make build && make clean

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then make build-all && make package; fi;

deploy:
  provider: releases
  api_key:
    secure: C0tfO8c4ZwjaJMkrAphlzDq3Sh4rhZ+uA/JXgdLDg+3HArEnwvtqkbnzRVo9BGMCZU73YTR6DVO/X7qsBV5y5Pu4beDVq/isREmY2S4nCs7X77XXW9XY3IvWuPD3nc009mgv9LjwV3AlsS0vVF684VYNoEDj/Fqr2gXXhLWUHYNBPF16mCaKXiHy8Epwi1iE4AOKhNdjd1J1j/xMSGYF+t9DNk5QXHXEgfVZ6PCpF4yiSda/ySv2OPsJK58LlmqsJe3sfllnQipmKXa7blOiEThke1PG0HNQB5hhuihI1nKaPho+7MOF+BA5rlQMB5ux0FeUTJS6hhIJp+IiAz0sJ2aA+tM6wkRXpl7u+l3RbDiMo5JgGBKYr1R3kRu9R9zK3/FN9u5ZCNBKOSF/NLUybMJV78klpm+IQqQ7Qjy/LmramDBdGWY4i5BnCtr157jkpbfWqz0Xjh1c2gWgupQsqmcSc3Nvney3JoryFbu+4XdBwmw64xnDcxsxfu//Xn2zDVvs0coaNqLFzPi0+BkHWIHt5/ad1vQDHLEnpK+blV4vRw7hY4uqe9xQeO6EakEWnvPsnWWrn+wfu39Ddz16HWzq1ze2KQXwxSWd02qhHtN14APxl8Vr3l98tCBAvXnE/kNl7ZMpX+Au+yguzZQ4Ej8q7Uqj9q5KvIzTsOr7Kq8=
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
