language: go

go:
  - 1.7
  - tip

addons:
  apt:
    packages:
      - xclip

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - go test -v

script:
  - go build -o bin/snpt -i .

matrix:
  allow_failures:
    - go: tip
