language: go

go:
  - 1.8
  - tip

cache:
  directories:
    - vendor

env:
  global:
    # coveralls repo token
    - secure: N9SmiHqmT62JBF4+ChXXrYKdIfTZ7nHkcQHnSRzyZ4ii00uY9g9w/8nWPGaGBJ4WGoaCUJx+VkVCS1UOf/UbZ8CqST89LE5EFc2N4AnqFSA3iRA3BlTb1OehppdYSA9GdrmX+NbaDJNdaqgOiz+JpBvbno2+hP0jXQPPqEhQKlRlP+I4QlwYtWiHm+iwoNP88kmunBj+G/qe79kq0qflQOFcZQIujORWjNLGNKepA06Bnb3Yi42EihXCQP7BbXWgKhp3SVTvIAL7wfEYjTOmPRXvU+bs8O7DI/C002CfnyiE00/KzKNaD+ICRiBh33ew3wD3FraLuXlWJ9BDNXKjfv04y0Mif/oERHc2Y08BNuQAFnlD2QCMrze6bRrJRf0Z5wD9tQn52BhP6w9qnxmMXitDu+j9uUj81wNz9uiEdFm+bZvn0HKHcgMzye9VCsPXRhmAABlr9XlGY+vjiiaguiWM/d6x87CtTBZva9FVZkfd3UY61X2L4vSIYuGOQe86GJFb4w8u71iD1Do4lnp/mKXRymeUgMTWIyF2meZK/7gF1TwLxskmvgeEBZ7uTSpsU+iNuIV4hzmPn5IAQgQQc4RqFPOHP7ZqvRvA++cImTHk5IW78KW0B2Ca2QPJHXNekHuAMJV65VSnhh4h4r3GpLh15rAMqx+Ud2BFsRzWxuY=

before_script:
  - make install-env-deps
  - make install
  # So we can use find -execdir on travis - https://github.com/travis-ci/travis-ci/issues/4862
  - PATH=${PATH//:\.\/node_modules\/\.bin/}

script:
  - make lint
  - make test && make coverage
  - make build && make clean

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then make build-all && make package; fi;

matrix:
  allow_failures:
    - go: tip

deploy:
  provider: releases
  api_key:
    secure: KqhQTRZx6Y0Hdu9HQ14avC7i2OvA60tPC5rbpNQih/MI8bb8JEncMYcE9Ntyr4NKtXf9vY5X7klIKc77gTGecSMarIlukaN/WJb5t35ZOC38d1py7P9u6qBkS9yPmR+13AavQyBROJx29H4TBbFVbGfl3ELepNKg6ivA8XR6n4xSfPR+xjydPT1p8E69Ux5h+S9+qfQ1aa002aB1vrLm5wVnrJuaE4PjO2d7JuQcXnJFfqyI/dG9OTCDvkuGETIWMf7P9eq6YzMIQJoJ8ey8S0ErEBGloKT4QfpAZf24L5ZalxuGtzMdFBhtxVr6IGB7eouoUqf1I0oNUol+ihsdRkWFOIKN4nHB2kuKLDzL2uM76rmEXDA4+cQS1kgQyr7GSoPaB9pvByl1ITl7JA0u7HIYlkqPB2wMVq5Y2KG38rkuc8V+yAUFdJCL5lXMV+F7r/zJFTB6TjedBY4Oh/O0v8yhl7NlHL6rat11+g6hi3sn3a0sBN+xChk74TbQ+oj7UDOfl+9+cINlLVq3+GIjqFNPcPP1uMmXzGpW+neh+mWg0ncc8o6lnlSalBvEBTJ8fKseJatFGLC+A49Nt+0YxPiBtJKIpdaFGlbaUqGBiH7us7K6aIdymAE9p2P58lr9HJMgdzABxDnjiqczJkk9/qYgaWNOaD8pFd2GR0Btmic=
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
