
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ararog/timeago"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/atotto/clipboard"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "github.com/segmentio/go-prompt"
  revision = "f0d19b6901ade831d5a3204edc0d6a7d6457fbb2"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/afero"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
