name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: true

jobs:
  snpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup project
        run: make install

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.1

      - name: Run tests
        run: make test

      - name: Generate test coverage
        run: make coverage

      - name: Build binary
        run: make build

      - name: Upload test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=github
