name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  snpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: false

      - name: Setup project
        run: make install

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: ./

      - name: Run tests
        run: make test

      - name: Generate test coverage
        run: make coverage

      - name: Build binary
        run: make build

      - name: Upload test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=coverage.out -service=github
