name: Release

on:
  push:
    tags: ['*']

jobs:
  snpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: false

      - name: Setup project
        run: make install

      - name: Setup env
        run: echo ::set-env name=TAG::${GITHUB_REF#refs/*/}

      - name: Build binaries
        run: make build-all

      - name: Package binaries
        run: make package

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/*.tar.gz
          token: ${{ secrets.DEPLOY_TOKEN }}
